scripts:
- name: My script
  command: python3 ./examples/example.py
  description: Prints the name to the console
  args:
  - type: string
    name: Employee name
    description: the name of the employee to say 'woo' to
  - type: number
    name: Times
    description: the number of times to say 'woo'
- name: My other script!!
  command: python3 example2.py
  description: Prints 'happy birthday' to the console
  args:
  - type: string
    name: Friend name
    description: the name of the friend with the birthday
